### ISSUE TITLE
@embedded types still have `_id` field in mongodb

### ISSUE THREAD

**Issue by playerx** [prisma/Mongo-Connector-Preview#14]
When applied data model with embedded type and inserted some data, `_id` field was created for @embedded type in mongo db

**Comment by do4gr** [comment]
We decided to create _id fields for embedded types when they are created by Prisma in order to have the option to expose one unique field and the operations that it enables - like update and delete. This is not yet reflected in the docs but will be changed soon. 

Prisma will be able to work with existing Mongo databases that do not have these id fields.

**Comment by playerx** [comment]
Got it, thanks for the info
